### ISSUE TITLE
Measure page engagement

### ISSUE THREAD

**Issue by theninj4** [holidayextras/barometer#11]
We could measure how long users spend on each page. We know how many views each page gets and how long pages take to load, it'd be awesome to measure how effective each page is. We'd be measuring either page load until page unload, or time between dynamic page loads. We could use that data to help prioritise where we focus development effort.

**Comment by msaspence** [comment]
Unload might be hard to do reliably, but I don't think it would matter to much if you only got a subset of sessions. The problem could be that (if #6 was implemented) you might end up with a sample that is weight towards modern browsers and poorly represents older browsers that don't support the Beacon API.
