### ISSUE TITLE
Ready states in IE are different

### ISSUE THREAD

**Issue by msaspence** [holidayextras/barometer#17]
> The state names are different in Internet Explorer. Instead of UNSENT, OPENED, HEADERS_RECEIVED, LOADING and DONE, the names READYSTATE_UNINITIALIZED (0), READYSTATE_LOADING (1), READYSTATE_LOADED (2), READYSTATE_INTERACTIVE (3) and READYSTATE_COMPLETE (4) are used.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState

**Comment by theninj4** [comment]
This doesn't actually make a difference - the state `names` are different, but we look them up based on `id` and map them to a name for the sake of a readable metric :+1:
