### ISSUE TITLE
Flush buffer on unload clue

### ISSUE THREAD

**Issue by msaspence** [holidayextras/barometer#5]
On older browsers that don't support `sendBeacon` we can't block the unload and send the data, because we can't sent a timeout on that and on a slow network could prevent the tab from closing for some time.

We could however look for clues that they are about to close the window and flush the buffer then. These could include: 
 * The mouse leaving the view area
 * ctrl or cmd being pressed

**Comment by theninj4** [comment]
Moving the mouse of the window is already implemented, however watching for key presses is a neat idea. :+1:
