### ISSUE TITLE
Send payloads with sendBeacon

### ISSUE THREAD

**Issue by msaspence** [holidayextras/barometer#6]
Browsers that [support it](http://caniuse.com/#feat=beacon) can use the [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) to send data payloads. This will prevent the closing of the window causing any problems with the sending of data.

**Comment by theninj4** [comment]
Great idea, providing we can keep the final payload size down :+1: 

Reading the example in the linked documentation, the unload JS may be wrong right now - it doesn't opt into the synchronous XHR:
```javascript
client.open("POST", "/log", false); // third parameter indicates sync xhr
```

**Comment by msaspence** [comment]
The Beacon API is super terse so I don't think size will be a problem.

I don't think that we should do synchronous XHR for unload, as you can't set a timeout on it, if the request stalls then it's going to lock up the closing of the users window. Hence the suggest to try and preempt it #5 (I see that is already done, minus the keypress).

**Comment by msaspence** [comment]
@theninj4 I think we can close this now
